In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5]

In [3]:
a=np.array(list)

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.shape

(5,)

In [6]:

l1=[1,2,3]
l2=[5,6,7]
l3=[8,9,10]

In [8]:
a2=np.array([l1,l2,l3])

In [9]:
a2

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
a2.shape

(3, 3)

In [12]:
a2.reshape(9,1)
##reshape is used to transform size of 2d arrays

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])